dependencies:
  - name: cassandra
    repository: https://charts.bitnami.com/bitnami
    version: 9.1.3
    heap:
      size: 500M
      newGenSize: 200M
    datacenters:
      - name: dc1
        size: 3
